### ISSUE TITLE
Cache rlp in deserialized Serializable

### ISSUE THREAD

**Issue by heikoheiko** [ethereum/pyrlp#12]
We are heavily using rlp encoding of instances for generating their hashes. 

If we received and deserialized them, they can considered to be not mutable, therefore we could cache the originating rlp for fast hash computation.

As a safeguard, deserialized instances could have setter properties for the fields which would raise NotImplementedError.

**Comment by ulope** [comment]
Raising NotImplementedError in a setter is actually not needed. Simply not defining a setter will suffice (and cause an AttributeError in case setting the property is attempted).

**Comment by jnnk** [comment]
- Serializable now has attributes `rlp_` and `mutable_` (trailing underscore to distinguish from possibly clashing field names)
- if `mutable_` is `False`, attempts to set field values throw a `ValueError`. Note that (1) `mutable_` is not recursive (i.e. `block.mutable_` and `block.header.mutable_` are independent, although they have the same value after initialization) and (2) changes of existing objects are not tracked (e.g. it does not prevent appending to a list).
- `rlp.decode(s)` sets `rlp_` to `s` and (implicitly by `deserialize`) `mutable_` to `False`.
- `rlp.encode(obj)` returns `obj.rlp_` if it's there
- `rlp.encode(obj, sedes=SomeClass)` ignores `rlp_` (because different serializers can lead to different rlp, e.g. `rlp.encode(tx, Transaction)` vs `rlp.encode(tx, UnsignedTransaction)`)

To mutate an immutable object, set `mutable_` to `False` and (if the changes are persistent) `rlp_` to `None`.
